# Generated by Django 6.1.1 on 2026-09-12 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchtitle',
            options={},
        ),
        migrations.RemoveField(
            model_name='researchtitle',
            name='is_published',
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='adviser',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='keywords',
            field=models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=500),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='program',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='school_year',
            field=models.CharField(blank=True, help_text='Example: 2025-2026', max_length=20),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='submitter_email',
            field=models.EmailField(blank=True, help_text='Optional email address for contacting the submitter.', max_length=254),
        ),
    ]
