# Generated by Django 6.1.1 on 2026-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchtitle',
            options={},
        ),
        migrations.RemoveField(
            model_name='researchtitle',
            name='is_published',
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
