# Generated by Django 6.1.1 on 2026-09-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_researchtitle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='document',
            field=models.FileField(max_length=500, upload_to='research/papers/'),
        ),
    ]
