# Generated by Django 6.1.1 on 2026-09-13 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_alter_researchpaper_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='researchtitle',
            index=models.Index(fields=['publication_status', '-created_at'], name='research_pub_created_idx'),
        ),
    ]
