# Generated by Django 6.1.1 on 2026-09-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_researchtitle_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtitle',
            name='submitter_email',
            field=models.EmailField(blank=True, help_text='Optional email address for contacting the submitter.', max_length=254),
        ),
    ]
