# Generated by Django 6.1.1 on 2026-09-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchtitle_submitter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchtitle',
            name='adviser',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='keywords',
            field=models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=500),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='program',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researchtitle',
            name='school_year',
            field=models.CharField(blank=True, help_text='Example: 2025-2026', max_length=20),
        ),
    ]
